trigger:
  branches:
    include:
      - main

variables:
  imageName: unicx-integration
  acrName: unicxacr
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker image
    jobs:
      - job: DockerBuild
        displayName: Build and Push to ACR
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: 'unicxacr'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
                latest

  - stage: DeployToAKS
    displayName: Deploy using Helm
    dependsOn: BuildAndPush
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: Helm Upgrade/Install
        environment: 'aks-prod'
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - task: HelmInstaller@1
                  inputs:
                    helmVersionToInstall: 'latest'

                - task: HelmDeploy@0
                  displayName: Helm upgrade
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: '2N5 GLOBAL'
                    azureResourceGroup: 'unicx-dev'
                    kubernetesCluster: 'unicxdev-aks-kubernetes'
                    command: 'upgrade'
                    chartType: 'FilePath'
                    chartPath: 'deployment/integration-chart'
                    releaseName: 'unicx'
                    valueFile: 'deployment/integration-chart/values.yaml'
                    overrideValues: |
                      image.repository=$(acrName).azurecr.io/$(imageName)
                      image.tag=$(tag)
                      replicaCount=2
                    install: true
