trigger:
  branches:
    include:
      - main

variables:
  imageName: unicx-integration
  acrName: unicxacr
  tag: '$(Build.BuildId)'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker image
    jobs:
      - job: DockerBuild
        displayName: Build and Push to ACR
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Build and Push
            inputs:
              containerRegistry: 'unicxacr'
              repository: '$(imageName)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              tags: |
                $(tag)
                latest