trigger:
  branches:
    include:
      - develop

variables:
  dockerRegistryServiceConnection: 'unicxacr'
  imageRepository: 'unicx-integration'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: BuildAndPush
    displayName: Build and Push Docker image
    jobs:
      - job: DockerBuild
        displayName: Build and Push to ACR

        steps:
        - checkout: self
          displayName: Checkout code

        - task: Docker@2
          displayName: Build and publish image to Azure Container Registry
          inputs:
            command: buildAndPush
            containerRegistry: $(dockerRegistryServiceConnection)
            repository: $(imageRepository)
            dockerfile: $(dockerfilePath)
            tags: |
              $(tag)
        # steps:
        #   - checkout: self
        #     displayName: Checkout code
          
        #   # Option 1: Using Azure CLI (requires service connection)
        #   # First, create a service connection in Azure DevOps:
        #   # Project Settings > Service connections > New service connection > Azure Resource Manager
        #   # Then update the azureSubscription variable above with the connection name
        #   - task: AzureCLI@2
        #     displayName: Build and Push Docker image to ACR
        #     inputs:
        #       azureSubscription: $(azureSubscription)
        #       scriptType: 'bash'
        #       scriptLocation: 'inlineScript'
        #       inlineScript: |
        #         set -e  # Exit on error
                
        #         # Display Azure context information
        #         echo "Azure subscription context:"
        #         az account show --output table
                
        #         # Verify we're in the correct resource group context
        #         echo "Checking resource group: $(azureResourceGroup)..."
        #         az group show --name $(azureResourceGroup) --output table || echo "Warning: Resource group not found or not accessible"
                
        #         # Login to Azure Container Registry
        #         echo "Logging into Azure Container Registry: $(acrName)..."
        #         az acr login --name $(acrName)
                
        #         # Verify Dockerfile exists
        #         if [ ! -f "Dockerfile" ]; then
        #           echo "Error: Dockerfile not found in current directory: $(pwd)"
        #           ls -la
        #           exit 1
        #         fi
                
        #         echo "Building Docker image..."
        #         docker build -f Dockerfile -t $(acrName).azurecr.io/$(imageName):$(tag) -t $(acrName).azurecr.io/$(imageName):latest .
                
        #         echo "Pushing Docker images..."
        #         docker push $(acrName).azurecr.io/$(imageName):$(tag)
        #         docker push $(acrName).azurecr.io/$(imageName):latest
                
        #         echo "Build and push completed successfully!"

  # - stage: DeployToAKS
  #   displayName: Deploy using Helm
  #   dependsOn: BuildAndPush
  #   condition: succeeded()
  #   jobs:
  #     - deployment: Deploy
  #       displayName: Helm Upgrade/Install
  #       environment: 'aks-prod'
  #       pool:
  #         vmImage: ubuntu-latest
  #       strategy:
  #         runOnce:
  #           deploy:
  #             steps:
  #               - task: HelmInstaller@1
  #                 inputs:
  #                   helmVersionToInstall: 'latest'

  #               - task: HelmDeploy@0
  #                 displayName: Helm upgrade
  #                 inputs:
  #                   connectionType: 'Azure Resource Manager'
  #                   azureSubscription: '2N5 GLOBAL'
  #                   azureResourceGroup: 'unicx-dev'
  #                   kubernetesCluster: 'unicxdev-aks-kubernetes'
  #                   command: 'upgrade'
  #                   chartType: 'FilePath'
  #                   chartPath: 'deployment/integration-chart'
  #                   releaseName: 'unicx'
  #                   valueFile: 'deployment/integration-chart/values.yaml'
  #                   overrideValues: |
  #                     image.repository=$(acrName).azurecr.io/$(imageName)
  #                     image.tag=$(tag)
  #                     replicaCount=2
  #                   install: true
